name: CI/CD

on:
  push:
    branches: [master]
jobs:
  build:
    runs-on: ubuntu-latest
    steps: 
      - name: 1. 检出分支
        uses: actions/checkout@v3

      - name: 2. 拉取配置文件
        uses: actions/checkout@v3
        with:
          repository: ${{ secrets.GIST_REPOSITORY}}
          token: ${{ secrets.GIST_TOKEN }}
          path: my-tools
          ssh-strict: 'ls && mv ${{ secrets.GIST_PATH}}/application.yml src/main/resources -f'

      - name: 3. 安装环境依赖
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: 4. 构建jar包
        run: mvn -B package --file pom.xml

      - name: 5. 复制jar包和运行脚本到服务器并运行jar包
        uses: appleboy/ssh-action@master 
        with:
          host: ${{ secrets.SSH_HOST }}
          port: ${{ secrets.SSH_PORT }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }} 
          files: |
              target/*.jar
              start.sh
          remote-path: ${{ secrets.SSH_REMOTE_PATH }}
          after-upload: |
              cd ${{ secrets.SSH_REMOTE_PATH }}
              /usr/bin/sh start.sh restart